defaults:  
  - _self_  
  - hydra.output_subdir: null
  - hp_configs: hp_config
  - override hydra/hydra_logging: disabled  
  - override hydra/job_logging: disabled

hydra:
  run:
    dir: .

hp:
  seed: 42
  batch_size: 8

dataset:
  dir: 'C:/Users/grego/Documents/NVIDIA DLI/Notebooks/My Notebooks/data/birds-20/'
  img_size: [224,224]
  mean: [0.485, 0.456, 0.406]
  std: [0.229, 0.224, 0.225]

testing:
  gpu_id: 0
  num_workers: 0

model:
  backbone: vit
  backbone_arch: vit-tiny
  tl_algo: swav
  exp_folder: "./"
  model_name: "best_model.pth"